# -*- coding: utf-8 -*-
"""EDA_Sales_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TOH53s1BvKxg2FjGqUUVa3LKoFN5l8Or
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("deepanshuverma0154/sales-dataset-of-ecommerce-electronic-products")

print("Path to dataset files:", path)

import numpy as np
import pandas as pd
import os

csv_path = os.path.join(path, "Updated_sales.csv")
df = pd.read_csv(csv_path)

"""### **Data Cleaning and EDA Using Pandas & Matplotlib**"""

df.head()

sales = df.copy()

sales.columns

sales.describe()

sales.info()

sales.shape

"""### **Finding Data Type of Each Column**"""

print(sales.dtypes)

sales['Product'].value_counts()

sales[sales['Product'].isna()]

sales.isnull().sum()

"""### **Remove Nan Values from Dataset**"""

before = sales.isnull().sum()

before

sales = sales.dropna()

after = sales.isnull().sum()
after

sales['Price Each'].value_counts()

sales['Price Each'].dtype

sales['Price Each'].unique()

sales['Price Each'] = pd.to_numeric(sales['Price Each'], errors='coerce')

sales['Price Each'].value_counts()

sales['Price Each'].isnull().sum()

sales['Price Each'].unique()

sales = sales[sales['Price Each'] != 'Price Each']

sales['Price Each'] = pd.to_numeric(sales['Price Each'], errors='coerce')

sales = sales.dropna(subset=['Price Each'])

sales['Price Each'].value_counts()

sales['Price Each'].isnull().sum()

"""### **Feature Engineering**"""

sales['Order Date'].value_counts()

sales['Order Date']

sales['Order Date'] = pd.to_datetime(sales['Order Date'],errors='coerce')

sales = sales.dropna(subset=['Order Date'])

sales['Year'] = sales['Order Date'].dt.year
sales['Month'] = sales['Order Date'].dt.month
sales['Hour'] = sales['Order Date'].dt.hour
sales['Day'] = sales['Order Date'].dt.day

sales[['Year', 'Month', 'Hour', 'Day']]

sales.columns

sales = sales.drop(columns=['Order Date'])

sales.columns

sales['Quantity Ordered'].value_counts()

sales['Quantity Ordered'].isnull().sum()

sales['Purchase Address'].value_counts()

sales['City'] = sales['Purchase Address'].apply(lambda x: x.split(',')[1].strip())

sales['State'] = sales['Purchase Address'].apply(lambda x: x.split(',')[2].split()[0].strip())

sales[['City', 'State']]

sales.drop(columns=['Purchase Address'])

sales.columns

sales['Quantity Ordered'].isnull().sum()

sales['Quantity Ordered'].value_counts()

sales['Quantity Ordered'].unique()

sales['Quantity Ordered'] = pd.to_numeric(sales['Quantity Ordered'], errors='coerce')

sales['Quantity Ordered'].dtype

sales.isnull().sum()

print(sales.dtypes)

sales

sales.shape

sales['Price Each'].describe()

import matplotlib.pyplot as plt

plt.hist(sales['Price Each'], bins=20, color='skyblue', edgecolor='black')
plt.title('Price Each Distribution')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

quantity_per_city = sales.groupby('City')['Quantity Ordered'].sum()

quantity_per_city.plot(kind='bar', color='green')
plt.title('City Wise Total Quantity Ordered')
plt.xlabel('City')
plt.ylabel('Total Quantity Ordered')
plt.show()

quantity_per_state = sales.groupby('State')['Quantity Ordered'].sum()

quantity_per_state.plot(kind='bar', color='skyblue')
plt.title('State wise Total Quantity Ordered')
plt.xlabel('State')
plt.ylabel('Total Quantity Ordered')
plt.show()

sales['Price Each'].max()

sales['Price Each'].min()

sales

oder_quantity_per_product = sales.groupby('Product')['Quantity Ordered'].sum().sort_values(ascending=False)
oder_quantity_per_product

oder_quantity_per_product.plot(kind='bar', color='red')
plt.title('Product Vs Ordered Quantity')
plt.xlabel('Product')
plt.ylabel('Total Quantity Ordered')
plt.show()

top_products = oder_quantity_per_product.head(10)
plt.figure(figsize=(8,8))
plt.pie(top_products, labels=top_products.index, autopct='%1.1f%%', startangle=140)
plt.title('Top 10 Products by Quantity Ordered')
plt.show()

product_counts = sales['Product'].value_counts()
product_counts

product_counts.plot(kind='bar', color='green')
plt.title('Product Sold Frequency')
plt.xlabel('Products')
plt.ylabel('Sold Count')
plt.show()

sales['Date Time'] = sales.apply(
    lambda row: pd.Timestamp(
        year=row['Year'],
        month=row['Month'],
        day=row['Day'],
        hour=row['Hour']
    ),
    axis=1
)

sales

sales['Sales'] = sales['Quantity Ordered'] * sales['Price Each']

daily_sales = sales.groupby(sales['Date Time'].dt.date)['Sales'].sum()
daily_sales

plt.figure(figsize=(12,6))
plt.plot(daily_sales.index, daily_sales.values, marker='o', color='blue')
plt.title('Daily Sales Trend')
plt.xlabel('Date')
plt.ylabel('Total Sales ($)')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()